# This is a configuration file for the continuous delivery service provided
# by AppVeyor.com. Its purpose is to automatically build both the 32
# and 64 bit versions of the Java Chromium Embedded Framework (JCEF).
# Please refer to https://bitbucket.org/chromiumembedded/java-cef
# for more information on JCEF.

os: Visual Studio 2015
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://www.us.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
  - cmd: SET PATH=C:\maven\apache-maven-3.2.5\bin;%PATH%
  - cmd: SET MAVEN_OPTS=-XX:MaxPermSize=2g -Xmx4g
  - cmd: SET JAVA_OPTS=-XX:MaxPermSize=2g -Xmx4g

clone_folder: c:\projects\java-org.cef\src

platform:
  - win32
  - x64

configuration:
  - Release

environment:
  matrix:
  - buildType: win32
    generatorName: Visual Studio 14
    JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
  - buildType: win64
    generatorName: Visual Studio 14 Win64
    JAVA_HOME: C:\Program Files\Java\jdk1.8.0

matrix:
  exclude:
    - platform: x64
      buildType: win32
    - platform: win32
      buildType: win64

before_build:
  - SET PATH=%JAVA_HOME%;%PATH%
  - echo "Running cmake..."
  - cd c:\projects\java-org.cef\src
  - mkdir jcef_build
  - cd jcef_build
  - cmake -G "%generatorName%" ..
  - echo "Building the JCEF Java classes..."
  - cd c:\projects\java-org.cef\src

after_build:
  - echo "Build Maven distribution..."
  - cd c:\projects\java-org.cef\src
  - mvn clean package --batch-mode -DskipTest
  - mvn clean install --batch-mode
  - cd  c:\projects\java-cef\src\target
  - 7z a jcef-%buildType%-distribution.zip ./*.jar
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2

artifacts:
  - path: target\jorg.cef-%buildType%-distribution.zip
    name: jcef-%buildType%-distribution
